# Generated by Django 3.1 on 2020-08-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
