# Generated by Django 3.1 on 2020-08-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_remove_category_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default=1, max_length=180, unique=True),
            preserve_default=False,
        ),
    ]
