# Generated by Django 3.1 on 2020-08-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_comments_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('time', models.DateTimeField(default=None, null=True)),
                ('contain', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
