# Generated by Django 3.1 on 2020-09-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
